use_frameworks!

target 'WMPageController-JQHover_Example' do
  pod 'WMPageController-JQHover', :path => '../'
  pod 'MJRefresh'
  target 'WMPageController-JQHover_Tests' do
    inherit! :search_paths

    
  end
end
